version: '3.4'

services:
  docentedb:
    container_name: docentedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DocenteDb
    restart: always
    ports:
        - "5434:5432"
    volumes:
      - postgres_docente:/var/lib/postgresql/data/ 

  # redis:
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"